import numpy as np
import matplotlib.pyplot as plt
import math
from airfoil import AirfoilData

class BEMT():
    # coding on blade-element momentum theory

    def __init__(self):
        # constants
        self.rho = 1.225 # kg/m^3, the air density

        # airfoil specification
        self.a_r = 0.1125  # [-/deg], the profile lift curve slope in the linear region NACA2414

        # specify initial rotor sizing parameters
        self.R = 3.5 # m, the rotor radius in meters
        self.b = 4 # - , number of blades
        self.omega = 40 # rad/s, rotational velocity



    def discretise(self, num_elements=4):

        #divide blade into elements
        self.r_list = [i * (self.R / num_elements) + 0.5 * (self.R / num_elements) for i in range(num_elements)]
        self.dr = (self.R / num_elements)

        #setup chord
        c_root = 0.2 # meters
        taper = 0.7 # -
        c_tip = c_root * taper
        self.c_r_list = []
        for r in self.r_list:
            c_r = c_root + ((c_tip - c_root)/self.R) * r
            self.c_r_list.append(c_r)

        #setup theta
        theta_root = np.radians(15)
        theta_tip = np.radians(2)
        self.theta_r_list = []
        for r in self.r_list:
            theta_r = theta_root + ((theta_tip - theta_root)/self.R) * r
            self.theta_r_list.append(theta_r)

        #setup airfoil progression
        self.a_r_list = []
        for n in range(num_elements):
            self.a_r_list.append(self.a_r)


    def vertical(self, omega=None, theta_r=None, c_r=None, r=None, dr=None, V_c=None, a_r=None):
        # define non-dimensionalised rotor radius position
        r_bar = r / self.R
        V_t = omega * self.R
        dr_bar = dr / self.R

        # compute induced velocity at point r
        induced_1 = (a_r * self.b * c_r)/(16 * math.pi * self.R)
        induced_2 = -1 * (induced_1 + (V_c / (2 * V_t)))
        induced_3 = math.sqrt((induced_1 + (V_c /(2 * V_t)))**2 + ((induced_1 * 2) * ((r_bar * theta_r) - (V_c / V_t))))
        v_r = V_t * (induced_2 + induced_3)

        phi = (V_c + v_r)/(omega * r)
        alpha = theta_r - phi
        self.alpha = alpha
        c_l_linear = a_r * alpha

        # drag for a blade element of size dr
        airfoildata = AirfoilData()
        interpolated_c_l, interpolated_c_d = airfoildata.interpolate_cl_cd(alpha)
        print(interpolated_c_d)

        # Lift for a blade element of size dr
        dDp_r = interpolated_c_d * 0.5 * self.rho * ((omega * r) ** 2) * c_r * dr

        # lift for a blade element of size dr
        dL_r = c_l_linear * 0.5 * self.rho * ((omega * r) ** 2) * c_r * dr

        # thrust generated by a blade element of size dr
        dT_r = dL_r - dDp_r * phi

        # torque needed for a blade element of size dr
        dQ_r = (dL_r * phi + dDp_r) * r
        dP_r = dQ_r * omega

        dP_ind = 4 * math.pi * (self.R ** 2) * self.rho * (v_r ** 3) * r_bar * dr_bar

        prop = [dL_r,dDp_r,dT_r,dQ_r,dP_r,dP_ind]
        return prop, v_r, c_l_linear



if __name__ == '__main__':
    BEMT = BEMT()

    #initialise discretisation and insert number of elements
    BEMT.discretise(num_elements=20)

    dL_r_list = []
    dDp_r_list = []
    dT_r_list = []
    dQ_r_list = []
    dP_r_list = []
    dP_ind_list = []

    for chord, theta, a, r in zip(BEMT.c_r_list, BEMT.theta_r_list, BEMT.a_r_list, BEMT.r_list):
        prop = BEMT.vertical(omega=BEMT.omega, theta_r=theta, c_r=chord, r=r, dr=BEMT.dr, a_r=a, V_c=1)
        dL_r_list.append(prop[0][0])
        dDp_r_list.append(prop[0][1])
        dT_r_list.append(prop[0][2])
        dQ_r_list.append(prop[0][3])
        dP_r_list.append(prop[0][4])
        dP_ind_list.append(prop[0][5])

    print(dL_r_list)
    print(f"L {sum(dL_r_list)*4}")
    print(dDp_r_list)
    print(f"D {sum(dDp_r_list)*4}")
    print(dT_r_list)
    print(f"T {sum(dT_r_list)*4}")
    print(dQ_r_list)
    print(f"Q {sum(dQ_r_list)*4}")
    print(dP_r_list)
    print(f"P_r {sum(dP_r_list)*4}")
    print(sum(dL_r_list)/sum(dDp_r_list))

    plt.plot(BEMT.r_list, dL_r_list)
    plt.xlabel("Spanwise radius [m]")
    plt.ylabel("Lift [N]")
    plt.show()





