import numpy as np
import matplotlib.pyplot as plt
import math
from airfoil import AirfoilData

class BEMT():
    # coding on blade-element momentum theory

    def __init__(self):
        # constants
        self.rho = 1.225 # kg/m^3, the air density

        # airfoil specification
        self.a_r = 0.1225 * (180 / np.pi)  # [-/deg], the profile lift curve slope in the linear region NACA2414

        # specify initial rotor sizing parameters
        self.R = 1 # m, the rotor radius in meters
        self.b = 5 # - , number of blades
        self.cutout = 0.1 * self.R
        self.r_bar_e = 0.95 #effective blade radius due to tip losses, approximate input for now

        #rotational velocity
        self.omega = 260 # rad/s, rotational velocity

        #numbre of rotors
        self.n_rotors = 10

    def discretise(self, num_elements=None):

        #divide blade into elements
        self.r_list = [i * (self.R / num_elements) + 0.5 * (self.R / num_elements) for i in range(num_elements)]
        self.dr = (self.R / num_elements)
        #print(self.r_list)

        #setup chord
        c_root = 0.08 # meters
        taper = 0.8 # -
        c_tip = c_root * taper
        c_avg = 0.5 * (c_root + c_root * taper)
        self.AR = (self.R - self.cutout) / c_avg

        #slope of the chord distribution
        slope_c = (c_tip - c_root)/(self.R - self.cutout)

        self.c_r_list = []
        for r in self.r_list:
            c_r = (c_root - (slope_c * self.cutout)) + (slope_c * r)
            self.c_r_list.append(c_r)
        #print(self.c_r_list)

        #setup theta
        theta_root = np.deg2rad(15)
        theta_tip = np.deg2rad(2)

        #slope of the twist distribution
        slope_t = (theta_tip - theta_root)/(self.R - self.cutout)

        self.theta_r_list = []
        for r in self.r_list:
            theta_r = (theta_root - (slope_t * self.cutout)) + (slope_t * r)
            self.theta_r_list.append(theta_r)

        #setup airfoil progression
        self.a_r_list = []
        for n in range(num_elements):
            self.a_r_list.append(self.a_r)

        #convert relative effective radius to absolute value
        self.r_e = self.r_bar_e * self.R


    def vertical(self, omega=None, theta_r=None, c_r=None, r=None, dr=None, V_c=None, a_r=None):
        # define non-dimensionalised rotor radius position
        r_bar = r / self.R
        V_t = omega * self.R
        dr_bar = dr / self.R

        # compute induced velocity at point r
        induced_1 = (a_r * self.b * c_r)/(16 * math.pi * self.R)
        induced_2 = -1 * (induced_1 + (V_c / (2 * V_t)))
        induced_3 = math.sqrt((induced_1 + (V_c /(2 * V_t)))**2 + ((induced_1 * 2) * ((r_bar * theta_r) - (V_c / V_t))))
        v_r = V_t * (induced_2 + induced_3)

        phi = (V_c + v_r)/(omega * r)
        alpha = theta_r - phi
        self.alpha = alpha
        c_l_linear = a_r * alpha

        # drag for a blade element of size dr
        airfoildata = AirfoilData()
        interpolated_c_l, interpolated_c_d = airfoildata.interpolate_cl_cd(alpha)

        # lift for a blade element of size dr
        dL_r = c_l_linear * 0.5 * self.rho * ((omega * r) ** 2) * c_r * dr

        # Lift for a blade element of size dr
        dDp_r = interpolated_c_d * 0.5 * self.rho * ((omega * r) ** 2) * c_r * dr

        # thrust generated by a blade element of size dr
        dT_r = dL_r - dDp_r * phi

        # torque needed for a blade element of size dr
        dQ_r = (dL_r * phi + dDp_r) * r
        dP_r = dQ_r * omega

        dP_ind = 4 * math.pi * (self.R ** 2) * self.rho * (v_r ** 3) * r_bar * dr_bar

        prop = [dL_r,dDp_r,dT_r,dQ_r,dP_r,dP_ind]
        return prop, v_r, c_l_linear

    def forward(self, r=None, omega=None, V_f=None, gamma=None, psi=None, alpha_v=None, theta_r=None, dr=None, a_r=None, c_r=None):
        # define non-dimensionalised rotor radius position
        r_bar = r / self.R
        V_t = omega * self.R
        dr_bar = dr / self.R

        # compute induced velocity at point r
        induced_1 = (a_r * self.b * c_r) / (16 * math.pi * self.R)
        induced_2 = -1 * (induced_1 + (V_c / (2 * V_t)))
        induced_3 = math.sqrt((induced_1 + (V_c / (2 * V_t))) ** 2 + ((induced_1 * 2) * ((r_bar * theta_r) - (V_c / V_t))))
        v_r = V_t * (induced_2 + induced_3)

        # flight velocities
        V_ho = -V_f * np.cos(gamma)
        V_c = V_f * np.sin(gamma)

        # axial and in-plane
        V_ax = -V_c + V_ho * alpha_v

        # velocity perpendicular to the blade varying with r and psi
        U_orth = self.omega * r + V_ho * psi

        # total axial velocity
        V_ax_tot = V_ax + v_r

        # angles
        phi = V_ax_tot/U_orth
        alpha = theta_r - phi

        # incoming air speed for the airfoil #NO ASSUMPTION ON SMALL ANGLE STUFF
        V_inflow = U_orth / np.cos(phi)

        c_l_linear = a_r * alpha

        # drag for a blade element of size dr
        airfoildata = AirfoilData()
        interpolated_c_l, interpolated_c_d = airfoildata.interpolate_cl_cd(alpha)

        # lift generated by a blade element dr
        dL_r = c_l_linear * 0.5 * self.rho * (V_inflow ** 2) * c_r * dr

        # drag generated by a blade element dr
        dDp_r = interpolated_c_d * 0.5 * self.rho * (V_inflow ** 2) * c_r * dr

        # thrust generated by a blade element dr
        dT_r = dL_r - dDp_r * phi

        # torque needed for a blade element dr at distance r from the rotating axis
        dQ_r = (dL_r * phi + dDp_r) * r


if __name__ == '__main__':
    BEMT = BEMT()

    #initialise discretisation and insert number of elements
    BEMT.discretise(num_elements=1000)

    dL_r_list = []
    dDp_r_list = []
    dT_r_list = []
    dQ_r_list = []
    dP_r_list = []
    dP_ind_list = []

    for chord, theta, a, r in zip(BEMT.c_r_list, BEMT.theta_r_list, BEMT.a_r_list, BEMT.r_list):
        prop = BEMT.vertical(omega=BEMT.omega, theta_r=theta, c_r=chord, r=r, dr=BEMT.dr, a_r=a, V_c=0)
        if BEMT.cutout<r<BEMT.r_e:
            dL_r_list.append(prop[0][0])
            dDp_r_list.append(prop[0][1])
            dT_r_list.append(prop[0][2])
            dQ_r_list.append(prop[0][3])
            dP_r_list.append(prop[0][4])
            dP_ind_list.append(prop[0][5])
        else:
            dL_r_list.append(0.0)
            dDp_r_list.append(0.0)
            dT_r_list.append(0.0)
            dQ_r_list.append(0.0)
            dP_r_list.append(0.0)
            dP_ind_list.append(0.0)

    # print(dL_r_list)
    # print(dDp_r_list)
    # print(dT_r_list)
    # print(dQ_r_list)
    # print(dP_r_list)

    #integration for one blade
    L = sum(dL_r_list)
    D = sum(dDp_r_list)
    T = sum(dT_r_list)
    Q = sum(dQ_r_list)
    P_r = sum(dP_r_list)
    LD = L/D

    print("---------------------")
    print(f"omega {BEMT.omega} [rad/s] or {9.549*BEMT.omega} [rpm]")
    print(f"L/D {LD} [-]")
    print(f"AR {BEMT.AR} [-]")
    print(f"R {BEMT.R} [m]")
    print("Other units in [N], [N*m], [W]")

    print("---------------------")
    print(f"one blade: (with induced velocity for b={BEMT.b})")
    print(f"L {L} D {D} T {T} Q {Q} P_r {P_r}")

    print("---------------------")
    print(f"for {BEMT.b} blades:")
    print(f"L {L*BEMT.b} D {D*BEMT.b} T {T*BEMT.b} Q {Q*BEMT.b} P_r {P_r*BEMT.b}")

    print("---------------------")
    print(f"for {BEMT.n_rotors} rotors:")
    print(f"L {L * BEMT.b * BEMT.n_rotors} D {D * BEMT.b * BEMT.n_rotors} T {T * BEMT.b * BEMT.n_rotors} Q {Q * BEMT.b * BEMT.n_rotors} P_r {P_r * BEMT.b * BEMT.n_rotors}")

    T_req = 7900
    n_rotor = T_req/(T*BEMT.b)
    print("---------------------")
    print(f"You would need {n_rotor} rotors to generate {T_req} [N] of thrust")

    plot = True
    if plot==True:
        plt.plot(BEMT.r_list, dL_r_list)
        plt.xlabel("Spanwise radius [m]")
        plt.ylabel("Lift [N]")
        plt.show()





