import numpy as np
import matplotlib.pyplot as plt
import math
from airfoil import AirfoilData


class BEMT():
    # coding on blade-element momentum theory

    def __init__(self):
        # constants
        self.rho = 1.225 # kg/m^3, the air density

        # airfoil specification
        self.a_r = 0.1225 * (180 / np.pi)  # [-/deg], the profile lift curve slope in the linear region NACA2414
        self.intercept_cl = 0.2379 #NACA2414

        # specify initial rotor sizing parameters
        self.R = 1.2 # m, the rotor radius in meters
        self.b = 6 # - , number of blades
        self.cutout = 0.15 * self.R
        self.r_bar_e = 0.95 #effective blade radius due to tip losses, approximate input for now

        #rotational velocity
        self.omega = 145 # rad/s, rotational velocity

        #numbre of rotors
        self.n_rotors = 3

    def discretise(self, num_elements=None):

        #divide blade into elements
        self.r_list = [i * (self.R / num_elements) + 0.5 * (self.R / num_elements) for i in range(num_elements)]
        self.dr = (self.R / num_elements)
        #print(self.r_list)

        #setup chord
        c_root = 0.1 # meters
        taper = 1 # -
        c_tip = c_root * taper
        c_avg = 0.5 * (c_root + c_root * taper)
        self.AR = (self.R - self.cutout) / c_avg

        #slope of the chord distribution
        slope_c = (c_tip - c_root)/(self.R - self.cutout)

        self.c_r_list = []
        for r in self.r_list:
            c_r = (c_root - (slope_c * self.cutout)) + (slope_c * r)
            self.c_r_list.append(c_r)
        #print(self.c_r_list)

        #setup theta
        theta_root = np.deg2rad(20)
        theta_tip = np.deg2rad(5)

        #slope of the twist distribution
        slope_t = (theta_tip - theta_root)/(self.R - self.cutout)

        self.theta_r_list = []
        for r in self.r_list:
            theta_r = (theta_root - (slope_t * self.cutout)) + (slope_t * r)
            self.theta_r_list.append(theta_r)

        #setup airfoil progression
        self.a_r_list = []
        for n in range(num_elements):
            self.a_r_list.append(self.a_r)

        #convert relative effective radius to absolute value
        self.r_e = self.r_bar_e * self.R

        #setup psi list
        self.psi_elements = 120
        self.psi_list = np.linspace(0, 2 * np.pi, self.psi_elements+1).tolist()

    def vertical(self, omega=None, theta_r=None, c_r=None, r=None, dr=None, V_c=None, a_r=None):
        # define non-dimensionalised rotor radius position
        r_bar = r / self.R
        V_t = omega * self.R
        dr_bar = dr / self.R

        # compute induced velocity at point r
        induced_1 = (a_r * self.b * c_r)/(16 * math.pi * self.R)
        induced_2 = -1 * (induced_1 + (V_c / (2 * V_t)))
        induced_3 = math.sqrt((induced_1 + (V_c /(2 * V_t)))**2 + ((induced_1 * 2) * ((r_bar * theta_r) - (V_c / V_t))))
        v_r = V_t * (induced_2 + induced_3)

        phi = np.arctan((V_c + v_r)/(omega * r))
        alpha = theta_r - phi
        c_l_linear = a_r * alpha + self.intercept_cl

        #calculate hypothenuse of the omega r and the axial velocity
        U_r = np.hypot(omega * r, (V_c + v_r))

        # drag for a blade element of size dr
        interpolated_c_l, interpolated_c_d = AirfoilData().interpolate_cl_cd(alpha * (180/np.pi))

        stall = 0
        if interpolated_c_d==None:
            dL_r = 0.0
            dD_r = 0.0
            dT_r = 0.0
            dFx = 0.0
            dQ_r = 0.0
            dP_r = 0.0
            stall = 1
        else:
            # lift for a blade element of size dr
            dL_r = c_l_linear * 0.5 * self.rho * ((U_r) ** 2) * c_r * dr

            # Lift for a blade element of size dr
            dD_r = interpolated_c_d * 0.5 * self.rho * ((U_r) ** 2) * c_r * dr

            # thrust generated by a blade element of size dr
            dT_r = dL_r * np.cos(phi) - dD_r * np.sin(phi)

            # torque needed for a blade element of size dr
            dFx = dL_r * np.sin(phi) + dD_r * np.cos(phi)
            dQ_r = dFx * r
            dP_r = dQ_r * omega

        prop_1 = [dL_r,dD_r,dT_r,dQ_r,dP_r,dFx,alpha,v_r,stall]
        return prop_1

    def forward(self, r=None, omega=None, V_f=None, gamma=None, psi=None, alpha_v=None, theta_r=None, dr=None, a_r=None, c_r=None):
        # define non-dimensionalised rotor radius position
        r_bar = r / self.R
        V_t = omega * self.R
        dr_bar = dr / self.R

        # airflow velocities
        V_ho = V_f * np.cos(gamma)
        V_c = V_f * np.sin(gamma)

        # compute induced velocity at point r
        induced_1 = (a_r * self.b * c_r) / (16 * math.pi * self.R)
        induced_2 = -1 * (induced_1 + (V_c / (2 * V_t)))
        induced_3 = math.sqrt((induced_1 + (V_c / (2 * V_t))) ** 2 + ((induced_1 * 2) * ((r_bar * theta_r) - (V_c / V_t))))
        v_r = V_t * (induced_2 + induced_3)
        #print(f"v_r ={v_r}")

        # axial and in-plane
        V_ax = (V_c * np.cos(alpha_v)) + (-V_ho * np.sin(alpha_v))
        V_inp =  (V_ho * np.cos(alpha_v)) + (-V_c * np.sin(alpha_v))
        # print(f"V_ax ={V_ax}")
        # print(f"V_inp*sin(ps) ={V_inp*np.sin(psi)}")

        # velocity perpendicular to the blade varying with r and psi
        U_orth = self.omega * r + V_inp * np.sin(psi)
        # print(f"omega*r ={self.omega * r}")
        # print(f"U_orth ={U_orth}")

        # total axial velocity
        V_ax_tot = V_ax + v_r

        # angles
        phi = np.arctan(V_ax_tot/U_orth)
        # print(f"phi = {phi * (180 / np.pi)}")
        alpha = theta_r - phi
        # print(f"alpha = {alpha * (180/np.pi)}")

        # incoming air speed for the airfoil #NO ASSUMPTION ON SMALL ANGLE STUFF
        V_inflow = np.hypot(U_orth,V_ax_tot)

        # cl computation
        c_l_linear = a_r * alpha + self.intercept_cl

        # drag for a blade element of size dr
        airfoildata = AirfoilData()
        interpolated_c_l, interpolated_c_d = airfoildata.interpolate_cl_cd(alpha * (180/np.pi))

        stall = 0
        if interpolated_c_d==None:
            dL_r = 0.0
            dD_r = 0.0
            dT_r = 0.0
            dFx = 0.0
            dQ_r = 0.0
            dP_r = 0.0
            stall = 1
        else:
            # lift generated by a blade element dr
            dL_r = c_l_linear * 0.5 * self.rho * (V_inflow ** 2) * c_r * dr

            # drag generated by a blade element dr
            dD_r = interpolated_c_d * 0.5 * self.rho * (V_inflow ** 2) * c_r * dr

            # thrust generated by a blade element dr
            dT_r = dL_r * np.cos(phi) - dD_r * np.sin(phi)

            # torque needed for a blade element dr at distance r from the rotating axis
            dFx = dL_r * np.sin(phi) + dD_r * np.cos(phi)
            dQ_r = dFx * r

            # profile power for a blade element dr
            dP_r = dQ_r * omega

        prop_2 = [dL_r,dD_r,dT_r,dQ_r,dP_r,dFx,alpha,stall]
        return prop_2


if __name__ == '__main__':
    BEMT = BEMT()

    #which analysis
    vertical = True
    forward = True

    #initialise discretisation and insert number of elements (minimum 100 for accuracy)
    num_elements = 100
    BEMT.discretise(num_elements=num_elements)

    if vertical==True:
        print("––––––––––––––––––––––––––––––––––––––––––––––")
        print("\033[34mVertical Flight:\033[0m")

        #specify vertical flight regime
        V_c = 0.0

        dL_r_list1 = []
        dD_r_list1 = []
        dT_r_list1 = []
        dQ_r_list1 = []
        dP_r_list1 = []
        dFx_r_list1 = []
        alpha_r_list1 = []
        v_r_list1 = []
        stall_r_list1 = []

        for chord, theta, a, r in zip(BEMT.c_r_list, BEMT.theta_r_list, BEMT.a_r_list, BEMT.r_list):
            prop_1 = BEMT.vertical(omega=BEMT.omega, theta_r=theta, c_r=chord, r=r, dr=BEMT.dr, a_r=a, V_c=V_c)
            if BEMT.cutout<r<BEMT.r_e:
                dL_r_list1.append(prop_1[0])
                dD_r_list1.append(prop_1[1])
                dT_r_list1.append(prop_1[2])
                dQ_r_list1.append(prop_1[3])
                dP_r_list1.append(prop_1[4])
                dFx_r_list1.append(prop_1[5])
                alpha_r_list1.append(prop_1[6])
                v_r_list1.append(prop_1[7])
                stall_r_list1.append(prop_1[8])

            else:
                dL_r_list1.append(0.0)
                dD_r_list1.append(0.0)
                dT_r_list1.append(0.0)
                dQ_r_list1.append(0.0)
                dP_r_list1.append(0.0)
                dFx_r_list1.append(0.0)
                alpha_r_list1.append(0.0)
                v_r_list1.append(0.0)
                stall_r_list1.append(0.0)

        #integration for one blade
        L = sum(dL_r_list1)
        D = sum(dD_r_list1)
        T = sum(dT_r_list1)
        Q = sum(dQ_r_list1)
        P_r = sum(dP_r_list1)
        Fx = sum(dFx_r_list1)

        print(alpha_r_list1[0])

        LD = L / D
        TFx = T / Fx
        C_T = T / (math.pi * (BEMT.R ** 2) * BEMT.rho * ((BEMT.omega * BEMT.R) ** 2))
        C_Q = Q / (math.pi * (BEMT.R ** 3) * BEMT.rho * ((BEMT.omega * BEMT.R) ** 2))
        C_P = P_r / (math.pi * (BEMT.R ** 2) * BEMT.rho * ((BEMT.omega * BEMT.R) ** 3))
        stall_factor = stall_r_list1.count(1)/num_elements

        print("---------------------")
        print(f"V_c {V_c}")
        print(f"omega {BEMT.omega} [rad/s] or {9.549*BEMT.omega} [rpm]")
        print(f"L/D {LD} [-]")
        print(f"T/Fx {TFx} [-]")
        print(f"AR {BEMT.AR} [-]")
        print(f"R {BEMT.R} [m]")
        print(f"C_T {C_T}")
        print(f"C_Q {C_Q}")
        print(f"C_P {C_P}")
        print(f"Stall occurence {stall_factor}")
        print("Other units in [N], [N*m], [W]")

        print("---------------------")
        print(f"one blade: (with induced velocity for b={BEMT.b})")
        print(f"L {L} D {D} T {T} Q {Q} P_r {P_r} Fx {Fx}")

        print("---------------------")
        print(f"for {BEMT.b} blades:")
        print(f"L {L*BEMT.b} D {D*BEMT.b} T {T*BEMT.b} Q {Q*BEMT.b} P_r {P_r*BEMT.b}  Fx {Fx*BEMT.b}")

        print("---------------------")
        print(f"for {BEMT.n_rotors} rotors:")
        print(f"L {L * BEMT.b * BEMT.n_rotors} D {D * BEMT.b * BEMT.n_rotors} T {T * BEMT.b * BEMT.n_rotors} Q {Q * BEMT.b * BEMT.n_rotors} P_r {P_r * BEMT.b * BEMT.n_rotors}  Fx {Fx * BEMT.b * BEMT.n_rotors}")

        T_req = 7758.73
        n_rotor = T_req/(T*BEMT.b)
        print("---------------------")
        print(f"You would need {n_rotor} rotors to generate {T_req} [N] of thrust")

        plot = False
        if plot==True:
            fig, axes = plt.subplots(4, 1, figsize=(8, 10), sharex=True)

            axes[0].plot(BEMT.r_list, dL_r_list1)
            axes[0].set_ylabel("Lift [N]")

            axes[1].plot(BEMT.r_list, dD_r_list1)
            axes[1].set_ylabel("Drag [N]")

            axes[2].plot(BEMT.r_list, alpha_r_list1)
            axes[2].set_ylabel("alpha [rad]")

            axes[3].plot(BEMT.r_list, v_r_list1)
            axes[3].set_ylabel("Induced velocity [m/s]")
            axes[3].set_xlabel("Radial position [m]")

            plt.show()

    if forward==True:
        print("––––––––––––––––––––––––––––––––––––––––––––––")
        print("\033[32mForward flight:\033[0m")

        #specify forward flight regime
        V_f = 22
        gamma = 0.0
        alpha_v = 5 * (np.pi/180) #in radians


        dL_r_list2 = []
        dD_r_list2 = []
        dT_r_list2 = []
        dQ_r_list2 = []
        dP_r_list2 = []
        dFx_r_list2 = []
        alpha_r_list2 = []
        stall_r_list2 = []

        dL_r_list3 = []
        dD_r_list3 = []
        dT_r_list3 = []
        dQ_r_list3 = []
        dP_r_list3 = []
        dFx_r_list3 = []
        alpha_r_list3 = []
        stall_r_list3 = []

        L = 0
        D = 0
        T = 0
        Q = 0
        P = 0
        Fx = 0

        for psi in BEMT.psi_list:
            #print(f"psi = {psi*(180/np.pi)}")
            for chord, theta, a, r in zip(BEMT.c_r_list, BEMT.theta_r_list, BEMT.a_r_list, BEMT.r_list):
                #print(f"r = {r}")
                if BEMT.cutout<r<BEMT.r_e:
                    prop_2 = BEMT.forward(omega=BEMT.omega, theta_r=theta, c_r=chord, r=r, dr=BEMT.dr, a_r=a, V_f=V_f, gamma=gamma, psi=psi, alpha_v=alpha_v)
                    dL_r_list3.append(prop_2[0])
                    dD_r_list3.append(prop_2[1])
                    dT_r_list3.append(prop_2[2])
                    dQ_r_list3.append(prop_2[3])
                    dP_r_list3.append(prop_2[4])
                    dFx_r_list3.append(prop_2[5])
                    alpha_r_list3.append(prop_2[6])
                    stall_r_list3.append(prop_2[7])
                else:
                    dL_r_list3.append(0.0)
                    dD_r_list3.append(0.0)
                    dT_r_list3.append(0.0)
                    dQ_r_list3.append(0.0)
                    dP_r_list3.append(0.0)
                    dFx_r_list3.append(0.0)
                    alpha_r_list3.append(0.0)
                    stall_r_list3.append(0.0)

            dL_r_list2.append(dL_r_list3)
            L += sum(dL_r_list3)

            dD_r_list2.append(dD_r_list3)
            D += sum(dD_r_list3)

            dT_r_list2.append(dT_r_list3)
            T += sum(dT_r_list3)

            dQ_r_list2.append(dQ_r_list3)
            Q += sum(dQ_r_list3)

            dP_r_list2.append(dP_r_list3)
            P += sum(dP_r_list3)

            dFx_r_list2.append(dFx_r_list3)
            Fx += sum(dFx_r_list3)

            alpha_r_list2.append(alpha_r_list3)
            stall_r_list2.append(stall_r_list3.count(1))

            dL_r_list3 = []
            dD_r_list3 = []
            dT_r_list3 = []
            dQ_r_list3 = []
            dP_r_list3 = []
            dFx_r_list3 = []
            alpha_r_list3 = []
            stall_r_list3 = []

        L = L / BEMT.psi_elements
        D = D / BEMT.psi_elements
        T = T / BEMT.psi_elements
        Q = Q / BEMT.psi_elements
        P = P / BEMT.psi_elements
        Fx = Fx / BEMT.psi_elements

        LD = L / D
        TFx = T / Fx
        C_T = T / (math.pi * (BEMT.R ** 2) * BEMT.rho * ((BEMT.omega * BEMT.R) ** 2))
        C_Q = Q / (math.pi * (BEMT.R ** 3) * BEMT.rho * ((BEMT.omega * BEMT.R) ** 2))
        C_P = P / (math.pi * (BEMT.R ** 2) * BEMT.rho * ((BEMT.omega * BEMT.R) ** 3))
        stall_factor = sum(stall_r_list2)/(num_elements*BEMT.psi_elements)
        print("---------------------")
        print(f"V_f {V_f} [m/s]")
        print(f"gamma {gamma}")
        print(f"alpha_v {alpha_v}")
        print(f"omega {BEMT.omega} [rad/s] or {9.549 * BEMT.omega} [rpm]")
        print(f"L/D {LD} [-]")
        print(f"T/Fx {TFx} [-]")
        print(f"AR {BEMT.AR} [-]")
        print(f"R {BEMT.R} [m]")
        print(f"C_T {C_T}")
        print(f"C_Q {C_Q}")
        print(f"C_P {C_P}")
        print(f"Stall occurence {stall_factor}")
        print("Other units in [N], [N*m], [W]")

        print("---------------------")
        print(f"one blade: (with induced velocity for b={BEMT.b})")
        print(f"L {L} D {D} T {T} Q {Q} P {P} Fx {Fx}")

        print("---------------------")
        print(f"for {BEMT.b} blades:")
        print(f"L {L * BEMT.b} D {D * BEMT.b} T {T * BEMT.b} Q {Q * BEMT.b} P_r {P * BEMT.b}  Fx {Fx * BEMT.b}")

        print("---------------------")
        print(f"for {BEMT.n_rotors} rotors:")
        print(f"L {L * BEMT.b * BEMT.n_rotors} D {D * BEMT.b * BEMT.n_rotors} T {T * BEMT.b * BEMT.n_rotors} Q {Q * BEMT.b * BEMT.n_rotors} P_r {P * BEMT.b * BEMT.n_rotors}  Fx {Fx * BEMT.b * BEMT.n_rotors}")

        T_req = 7758.73 / np.cos(alpha_v)
        n_rotor = T_req / (T * BEMT.b)
        print("---------------------")
        print(f"You would need {n_rotor} rotors to generate {T_req} [N] of thrust")

        plot = False
        if plot == True:

            plt.plot(BEMT.r_list, dL_r_list2[0])
            plt.plot(BEMT.r_list, dL_r_list2[30], color='k')
            plt.plot(BEMT.r_list, dL_r_list2[60])
            plt.plot(BEMT.r_list, dL_r_list2[90], color='b')
            haha = [(x + y + z + t)/4 for x, y, z, t in zip(dL_r_list2[0], dL_r_list2[30], dL_r_list2[60], dL_r_list2[90])]
            plt.plot(BEMT.r_list, haha, color='b')

            plt.show()

            plt.plot(BEMT.r_list, alpha_r_list2[0])
            plt.plot(BEMT.r_list, alpha_r_list2[30],color='k')
            plt.plot(BEMT.r_list, alpha_r_list2[60])
            plt.plot(BEMT.r_list, alpha_r_list2[90],color='b')
            plt.show()



