import numpy as np
import matplotlib.pyplot as plt
import math
from airfoil import AirfoilData
from scipy.interpolate import RegularGridInterpolator
from scipy.integrate import trapz


class BEMT():
    # coding on blade-element momentum theory

    def __init__(self):
        # constants  mn
        self.rho = 1.225 # kg/m^3, the air density

        # airfoil specification
        self.a_r = 0.102 * (180 / np.pi)  # [-/deg], the profile lift curve slope in the linear region NACA2414 0.1225 NACA6412 0.102
        self.intercept_cl = 0.6458 #NACA2414 0.2379 NACA6412 0.6458

        # specify initial rotor sizing parameters
        self.R = 1.22 # m, the rotor radius in meters
        self.b = 6 # - , number of blades
        self.cutout = 0.15 * self.R
        self.r_bar_e = 0.96 #effective blade radius due to tip losses, approximate input for now

        #rotational velocity
        self.omega = 120 # rad/s, rotational velocity

        #transition
        self.SOS = 343 # m/s, transition air speed

        #numbre of rotors
        self.n_rotors = 6

        #element structural properties
        self.E = 163 * (10**9) #Young's modulus in [Pa]
        self.I = 46053.4579 * (10**-12) #m^4

    def discretise(self, num_elements=None):

        #divide blade into elements
        self.r_list = [i * (self.R / num_elements) + 0.5 * (self.R / num_elements) for i in range(num_elements)]
        self.dr = (self.R / num_elements)
        #print(self.r_list)

        #setup chord
        c_root = 0.07 # meters
        taper = 0.8 # -
        c_tip = c_root * taper
        c_avg = 0.5 * (c_root + c_root * taper)
        self.AR = (self.R - self.cutout) / c_avg

        #slope of the chord distribution
        slope_c = (c_tip - c_root)/(self.R - self.cutout)

        self.c_r_list = []
        for r in self.r_list:
            c_r = (c_root - (slope_c * self.cutout)) + (slope_c * r)
            self.c_r_list.append(c_r)
        #print(self.c_r_list)

        #setup theta
        theta_root = np.deg2rad(10)
        theta_tip = np.deg2rad(5)

        #slope of the twist distribution
        slope_t = (theta_tip - theta_root)/(self.R - self.cutout)

        self.theta_r_list = []
        for r in self.r_list:
            theta_r = (theta_root - (slope_t * self.cutout)) + (slope_t * r)
            self.theta_r_list.append(theta_r)

        #setup airfoil progression
        self.a_r_list = []
        for n in range(num_elements):
            self.a_r_list.append(self.a_r)

        #convert relative effective radius to absolute value
        self.r_e = self.r_bar_e * self.R

        #setup psi list
        self.psi_elements = 120
        self.psi_list = np.linspace(0, 2 * np.pi, self.psi_elements+1).tolist()

    def vertical(self, omega=None, theta_r=None, c_r=None, r=None, dr=None, V_c=None, a_r=None):
        # define non-dimensionalised rotor radius position
        r_bar = r / self.R
        V_t = omega * self.R
        dr_bar = dr / self.R

        # compute induced velocity at point r
        induced_1 = (a_r * self.b * c_r)/(16 * math.pi * self.R)
        induced_2 = -1 * (induced_1 + (V_c / (2 * V_t)))
        induced_3 = math.sqrt((induced_1 + (V_c /(2 * V_t)))**2 + ((induced_1 * 2) * ((r_bar * theta_r) - (V_c / V_t))))
        v_r = V_t * (induced_2 + induced_3)

        # return self.number_of_blades * (self.C_l_alpha * (
        #             (pitch_equation(x) * (np.pi / 180)) - lambda_i / x) + c_l_intercept) * x * chord_equation(
        #     x) - 8 * lambda_i ** 2 * np.pi * self.rotor_radius
        #v_r = 5.8

        phi = np.arctan((V_c + v_r)/(omega * r))
        alpha = theta_r - phi
        c_l_linear = a_r * alpha + self.intercept_cl

        #calculate hypothenuse of the omega r and the axial velocity
        U_r = np.hypot(omega * r, (V_c + v_r))

        # mach number calculation
        M_r = U_r/self.SOS

        # drag for a blade element of size dr
        interpolated_c_l, interpolated_c_d = AirfoilData().interpolate_cl_cd(alpha * (180/np.pi))

        stall = 0
        if interpolated_c_d==None:
            dL_r = 0.0
            dD_r = 0.0
            dT_r = 0.0
            dFx = 0.0
            dQ_r = 0.0
            dP_r = 0.0
            stall = 1
            alpha = 0.0
        else:
            # lift for a blade element of size dr
            dL_r = c_l_linear * 0.5 * self.rho * ((U_r) ** 2) * c_r * dr

            # Lift for a blade element of size dr
            dD_r = interpolated_c_d * 0.5 * self.rho * ((U_r) ** 2) * c_r * dr

            # thrust generated by a blade element of size dr
            dT_r = dL_r * np.cos(phi) - dD_r * np.sin(phi)

            # torque needed for a blade element of size dr
            dFx = dL_r * np.sin(phi) + dD_r * np.cos(phi)
            dQ_r = dFx * r
            dP_r = dQ_r * omega

        prop_1 = [dL_r,dD_r,dT_r,dQ_r,dP_r,dFx,alpha,v_r,stall,M_r]
        return prop_1

    def forward(self, r=None, omega=None, V_f=None, gamma=None, psi=None, alpha_v=None, theta_r=None, dr=None, a_r=None, c_r=None, v_fl=None):
        # define non-dimensionalised rotor radius position
        r_bar = r / self.R
        V_t = omega * self.R
        dr_bar = dr / self.R

        # airflow velocities
        V_ho = V_f * np.cos(gamma)
        V_c = V_f * np.sin(gamma)

        # compute induced velocity at point r
        v_i_hov = self.induced()
        V_bar = V_f/v_i_hov
        alpha_disc = alpha_v + gamma
        array = np.array([0.0,0.0,0.0,0.0,0.0])
        array[0] = 1
        array[1] = 2 * V_bar * math.sin(alpha_disc)
        array[2] = (V_bar ** 2)
        array[3] = 0
        array[4] = -1
        roots = np.roots(array)[3]
        v_i_bar = np.real(roots)
        v_r = v_i_bar * v_i_hov

        # axial and in-plane
        V_ax = (V_c * np.cos(alpha_v)) + (-V_ho * np.sin(alpha_v))
        V_inp =  (V_ho * np.cos(alpha_v)) + (-V_c * np.sin(alpha_v))
        # print(f"V_ax ={V_ax}")
        # print(f"V_inp*sin(ps) ={V_inp*np.sin(psi)}")

        # velocity perpendicular to the blade varying with r and psi
        U_orth = self.omega * r + V_inp * np.sin(psi)
        # print(f"omega*r ={self.omega * r}")
        # print(f"U_orth ={U_orth}")

        # total axial velocity
        V_ax_tot = V_ax + v_r + v_fl

        # angles
        phi = np.arctan(V_ax_tot/U_orth)
        # print(f"phi = {phi * (180 / np.pi)}")
        alpha = theta_r - phi
        # print(f"alpha = {alpha * (180/np.pi)}")

        # incoming air speed for the airfoil #NO ASSUMPTION ON SMALL ANGLE STUFF
        V_inflow = np.hypot(U_orth,V_ax_tot)

        # cl computation
        c_l_linear = a_r * alpha + self.intercept_cl

        # drag for a blade element of size dr
        airfoildata = AirfoilData()
        interpolated_c_l, interpolated_c_d = airfoildata.interpolate_cl_cd(alpha * (180/np.pi))

        #compute mach number
        M_r = V_inflow / self.SOS

        stall = 0
        if interpolated_c_d==None:
            dL_r = 0.0
            dD_r = 0.0
            dT_r = 0.0
            dFx = 0.0
            dQ_r = 0.0
            dP_r = 0.0
            stall = 1
            alpha = 0.0
            dX = 0.0
        else:
            # lift generated by a blade element dr
            dL_r = c_l_linear * 0.5 * self.rho * (V_inflow ** 2) * c_r * dr

            # drag generated by a blade element dr
            dD_r = interpolated_c_d * 0.5 * self.rho * (V_inflow ** 2) * c_r * dr

            # thrust generated by a blade element dr
            dT_r = dL_r * np.cos(phi) - dD_r * np.sin(phi)

            # torque needed for a blade element dr at distance r from the rotating axis
            dFx = dL_r * np.sin(phi) + dD_r * np.cos(phi)
            dQ_r = dFx * r

            # profile power for a blade element dr
            dP_r = dQ_r * omega

            dX = dFx * np.sin(psi)

        #moments analysis
        dMom_r = dT_r * np.sin(psi)

        prop_2 = [dL_r,dD_r,dT_r,dQ_r,dP_r,dFx,alpha,stall,M_r,dMom_r,dX,v_r]
        return prop_2

    def flapping(self, dL_psi90=None, dL_psi270=None):
        #initiate displacement lists
        d_psi90 = []
        d_psi270 = []

        for dL in dL_psi90:
            i = dL_psi90.index(dL)
            sum_dL = sum(dL_psi90[:(i+1)])
            d_max = (11 * sum_dL * (self.r_list[i]**4))/(120 * self.E * self.I)
            d_psi90.append(d_max)

        sum_dl = 0.0
        d_max = 0.0

        for dL in dL_psi270:
            i = dL_psi270.index(dL)
            sum_dL = sum(dL_psi270[:(i+1)])
            d_max = (11 * sum_dL * (self.r_list[i]**4))/(120 * self.E * self.I)
            d_psi270.append(d_max)
        #print(f"d psi 90 {d_psi90[-5]}")
        #print(f"d psi 270 {d_psi270[-5]}")
        amp_r = [max - min for max, min in zip(d_psi90, d_psi270)]
        return amp_r

    def controlstability(self):
        # specify forward flight regime
        # specify forward flight regime
        V_f_values = np.linspace(0,50,10)
        gamma = 0.0
        alpha_v = np.linspace((-90*np.pi)/180, (90*np.pi)/180, num=10)

        results = {V_f: {'C_T': [], 'C_Fx': [], 'C_X': [], 'C_Q': [], 'C_P': []} for V_f in V_f_values}
        # Simulate for each V_f
        for V_f in V_f_values:
            for alpha_v_1 in alpha_v:
                print(alpha_v_1)
                dL_r_list2 = []
                dD_r_list2 = []
                dT_r_list2 = []
                dQ_r_list2 = []
                dP_r_list2 = []
                dFx_r_list2 = []
                alpha_r_list2 = []
                stall_r_list2 = []
                M_r_list2 = []
                dMom_r_list2 = []
                dX_r_list2 = []
                v_r_list2 = []

                dL_r_list3 = []
                dD_r_list3 = []
                dT_r_list3 = []
                dQ_r_list3 = []
                dP_r_list3 = []
                dFx_r_list3 = []
                alpha_r_list3 = []
                stall_r_list3 = []
                M_r_list3 = []
                dMom_r_list3 = []
                dX_r_list3 = []
                v_r_list3 = []

                L = 0
                D = 0
                T = 0
                Q = 0
                P = 0
                Fx = 0
                Mom = 0
                X = 0

                for psi in BEMT.psi_list:
                    # print(f"psi = {psi*(180/np.pi)}")
                    for chord, theta, a, r in zip(BEMT.c_r_list, BEMT.theta_r_list, BEMT.a_r_list, BEMT.r_list):
                        # print(f"r = {r}")
                        if BEMT.cutout < r < BEMT.r_e:
                            prop_2 = BEMT.forward(omega=BEMT.omega, theta_r=theta, c_r=chord, r=r, dr=BEMT.dr, a_r=a,
                                                  V_f=V_f, gamma=gamma, psi=psi, alpha_v=alpha_v_1, v_fl=0.0)
                            dL_r_list3.append(prop_2[0])
                        else:
                            dL_r_list3.append(0.0)

                    dL_r_list2.append(dL_r_list3)
                    L += sum(dL_r_list3)

                    dL_r_list3 = []

                # print(dL_r_list2[30],dL_r_list2[90])
                amp_r = BEMT.flapping(dL_psi90=dL_r_list2[30], dL_psi270=dL_r_list2[90])

                dL_r_list2 = []
                L = 0
                n = 1

                for i in range(n):
                    for psi in BEMT.psi_list:
                        # print(f"psi = {psi*(180/np.pi)}")
                        for chord, theta, a, r in zip(BEMT.c_r_list, BEMT.theta_r_list, BEMT.a_r_list, BEMT.r_list):
                            # print(f"r = {r}")
                            v_fl = amp_r[BEMT.r_list.index(r)] * np.cos(psi) * BEMT.omega
                            # print(v_fl)
                            if BEMT.cutout < r < BEMT.r_e:
                                prop_2 = BEMT.forward(omega=BEMT.omega, theta_r=theta, c_r=chord, r=r, dr=BEMT.dr,
                                                      a_r=a, V_f=V_f, gamma=gamma, psi=psi, alpha_v=alpha_v_1, v_fl=v_fl)
                                dL_r_list3.append(prop_2[0])
                                dD_r_list3.append(prop_2[1])
                                dT_r_list3.append(prop_2[2])
                                dQ_r_list3.append(prop_2[3])
                                dP_r_list3.append(prop_2[4])
                                dFx_r_list3.append(prop_2[5])
                                alpha_r_list3.append(prop_2[6])
                                stall_r_list3.append(prop_2[7])
                                M_r_list3.append(prop_2[8])
                                dMom_r_list3.append(prop_2[9])
                                dX_r_list3.append(prop_2[10])
                                v_r_list3.append(prop_2[11])
                            else:
                                dL_r_list3.append(0.0)
                                dD_r_list3.append(0.0)
                                dT_r_list3.append(0.0)
                                dQ_r_list3.append(0.0)
                                dP_r_list3.append(0.0)
                                dFx_r_list3.append(0.0)
                                alpha_r_list3.append(0.0)
                                stall_r_list3.append(0.0)
                                M_r_list3.append(0.0)
                                dMom_r_list3.append(0.0)
                                dX_r_list3.append(0.0)
                                v_r_list3.append(0.0)

                        dL_r_list2.append(dL_r_list3)
                        L += sum(dL_r_list3)

                        dD_r_list2.append(dD_r_list3)
                        D += sum(dD_r_list3)

                        dT_r_list2.append(dT_r_list3)
                        T += sum(dT_r_list3)

                        dQ_r_list2.append(dQ_r_list3)
                        Q += sum(dQ_r_list3)

                        dP_r_list2.append(dP_r_list3)
                        P += sum(dP_r_list3)

                        dFx_r_list2.append(dFx_r_list3)
                        Fx += sum(dFx_r_list3)

                        alpha_r_list2.append(alpha_r_list3)
                        stall_r_list2.append(stall_r_list3.count(1))
                        M_r_list2.append(max(M_r_list3))

                        dMom_r_list2.append(dMom_r_list3)
                        Mom += sum(dMom_r_list3)

                        dX_r_list2.append(dX_r_list3)
                        X += sum(dX_r_list3)

                        v_r_list2.append(v_r_list3)

                        dL_r_list3 = []
                        dD_r_list3 = []
                        dT_r_list3 = []
                        dQ_r_list3 = []
                        dP_r_list3 = []
                        dFx_r_list3 = []
                        alpha_r_list3 = []
                        stall_r_list3 = []
                        M_r_list3 = []
                        dMom_r_list3 = []
                        dX_r_list3 = []
                        v_r_list3 = []

                # print(stall_r_list2)
                T = T / BEMT.psi_elements
                Q = Q / BEMT.psi_elements
                P = P / BEMT.psi_elements
                Fx = Fx / BEMT.psi_elements
                X = X / BEMT.psi_elements

                C_T = (T * BEMT.b) / (math.pi * (BEMT.R ** 2) * BEMT.rho * (
                            (BEMT.omega * BEMT.R) ** 2))  # for the number of blades
                C_Fx = (Fx * BEMT.b) / (math.pi * (BEMT.R ** 2) * BEMT.rho * (
                            (BEMT.omega * BEMT.R) ** 2))  # for the number of blades
                C_X = (X * BEMT.b) / (math.pi * (BEMT.R ** 2) * BEMT.rho * (
                            (BEMT.omega * BEMT.R) ** 2))  # for the number of blades
                C_Q = (Q * BEMT.b) / (math.pi * (BEMT.R ** 3) * BEMT.rho * (
                            (BEMT.omega * BEMT.R) ** 2))  # for the number of blades
                C_P = (P * BEMT.b) / (math.pi * (BEMT.R ** 2) * BEMT.rho * (
                            (BEMT.omega * BEMT.R) ** 3))  # for the number of blades

                # Store results
                results[V_f]['C_T'].append(C_T)
                results[V_f]['C_Fx'].append(C_Fx)
                results[V_f]['C_X'].append(C_X)
                results[V_f]['C_Q'].append(C_Q)
                results[V_f]['C_P'].append(C_P)

        interpolate_C_T = True
        if interpolate_C_T==True:
            # Assuming `results` is already computed
            # Extract C_T as an example
            C_T_surface = np.array([results[V_f]['C_T'] for V_f in V_f_values])

            # Create interpolator for C_T
            interpolator = RegularGridInterpolator((V_f_values, alpha_v), C_T_surface)

            # Define a grid for interpolation
            V_f_query = np.linspace(0, 50, 100)  # Dense forward flight speeds
            alpha_v_query = np.linspace((-90 * np.pi) / 180, (90 * np.pi) / 180, 100)  # Dense alpha_v range

            # Create a mesh for query
            V_f_mesh, alpha_v_mesh = np.meshgrid(V_f_query, alpha_v_query)
            query_points = np.array([V_f_mesh.ravel(), alpha_v_mesh.ravel()]).T

            # Interpolate values
            C_T_interpolated = interpolator(query_points).reshape(V_f_mesh.shape)
            np.savetxt("C_T_interpolated.csv", C_T_interpolated, delimiter=",")

            # Plot 3D Interpolated Surface
            fig = plt.figure(figsize=(10, 10))
            ax = fig.add_subplot(111, projection='3d')
            surf = ax.plot_surface(alpha_v_mesh, V_f_mesh, C_T_interpolated, cmap='viridis', edgecolor='k')
            ax.set_xlabel('alpha_v (radians)')
            ax.set_ylabel('V_f (Forward Flight Speed)')
            ax.set_zlabel('C_T')
            ax.set_title('3D Interpolated Surface of C_T')
            fig.colorbar(surf, ax=ax, shrink=0.5, aspect=10)
            plt.show()

        interpolate_C_X = True
        if interpolate_C_X == True:
            # Assuming `results` is already computed
            # Extract C_T as an example
            C_X_surface = np.array([results[V_f]['C_X'] for V_f in V_f_values])

            # Create interpolator for C_X
            interpolator = RegularGridInterpolator((V_f_values, alpha_v), C_X_surface)

            # Define a grid for interpolation
            V_f_query = np.linspace(0, 50, 100)  # Dense forward flight speeds
            alpha_v_query = np.linspace((-90 * np.pi) / 180, (90 * np.pi) / 180, 100)  # Dense alpha_v range

            # Create a mesh for query
            V_f_mesh, alpha_v_mesh = np.meshgrid(V_f_query, alpha_v_query)
            query_points = np.array([V_f_mesh.ravel(), alpha_v_mesh.ravel()]).T

            # Interpolate values
            C_X_interpolated = interpolator(query_points).reshape(V_f_mesh.shape)
            np.savetxt("C_X_interpolated.csv", C_X_interpolated, delimiter=",")

            # Plot 3D Interpolated Surface
            fig = plt.figure(figsize=(10, 10))
            ax = fig.add_subplot(111, projection='3d')
            surf = ax.plot_surface(alpha_v_mesh, V_f_mesh, C_X_interpolated, cmap='viridis', edgecolor='k')
            ax.set_xlabel('alpha_v (radians)')
            ax.set_ylabel('V_f (Forward Flight Speed)')
            ax.set_zlabel('C_X')
            ax.set_title('3D Interpolated Surface of C_X')
            fig.colorbar(surf, ax=ax, shrink=0.5, aspect=10)
            plt.show()

        interpolate_C_Q = True
        if interpolate_C_Q == True:
            # Assuming `results` is already computed
            # Extract C_T as an example
            C_Q_surface = np.array([results[V_f]['C_Q'] for V_f in V_f_values])

            # Create interpolator for C_T
            interpolator = RegularGridInterpolator((V_f_values, alpha_v), C_Q_surface)

            # Define a grid for interpolation
            V_f_query = np.linspace(0, 50, 100)  # Dense forward flight speeds
            alpha_v_query = np.linspace((-90 * np.pi) / 180, (90 * np.pi) / 180, 100)  # Dense alpha_v range

            # Create a mesh for query
            V_f_mesh, alpha_v_mesh = np.meshgrid(V_f_query, alpha_v_query)
            query_points = np.array([V_f_mesh.ravel(), alpha_v_mesh.ravel()]).T

            # Interpolate values
            C_Q_interpolated = interpolator(query_points).reshape(V_f_mesh.shape)
            np.savetxt("C_Q_interpolated.csv", C_Q_interpolated, delimiter=",")

            # Plot 3D Interpolated Surface
            fig = plt.figure(figsize=(10, 10))
            ax = fig.add_subplot(111, projection='3d')
            surf = ax.plot_surface(alpha_v_mesh, V_f_mesh, C_Q_interpolated, cmap='viridis', edgecolor='k')
            ax.set_xlabel('alpha_v (radians)')
            ax.set_ylabel('V_f (Forward Flight Speed)')
            ax.set_zlabel('C_Q')
            ax.set_title('3D Interpolated Surface of C_Q')
            fig.colorbar(surf, ax=ax, shrink=0.5, aspect=10)
            plt.show()

        plot = True
        if plot==True:
            # Plot 2D Graphs
            fig, axs = plt.subplots(5, 1, figsize=(10, 15), sharex=True)
            colors = ['blue', 'green', 'red', 'orange']

            for i, V_f in enumerate(V_f_values):
                axs[0].plot(alpha_v, results[V_f]['C_T'], label=f"V_f={V_f}", color=colors[i % len(colors)])
                axs[1].plot(alpha_v, results[V_f]['C_Fx'], label=f"V_f={V_f}", color=colors[i % len(colors)])
                axs[2].plot(alpha_v, results[V_f]['C_X'], label=f"V_f={V_f}", color=colors[i % len(colors)])
                axs[3].plot(alpha_v, results[V_f]['C_Q'], label=f"V_f={V_f}", color=colors[i % len(colors)])
                axs[4].plot(alpha_v, results[V_f]['C_P'], label=f"V_f={V_f}", color=colors[i % len(colors)])

            # Set labels
            axs[0].set_ylabel('C_T')
            axs[1].set_ylabel('C_Fx')
            axs[2].set_ylabel('C_X')
            axs[3].set_ylabel('C_Q')
            axs[4].set_ylabel('C_P')
            axs[4].set_xlabel('alpha_v (radians)')
            axs[0].set_title('Coefficient Variation with Alpha_v for Different Forward Flight Speeds')

            # Add legends
            for ax in axs:
                ax.legend()

            plt.tight_layout()
            plt.show()

            # Plot 3D Surface
            fig = plt.figure(figsize=(10, 10))
            ax = fig.add_subplot(111, projection='3d')

            # Prepare data for 3D plotting
            alpha_v_mesh, V_f_mesh = np.meshgrid(alpha_v, V_f_values)
            C_T_surface = np.array([results[V_f]['C_T'] for V_f in V_f_values])

            # Plot surface
            surf = ax.plot_surface(alpha_v_mesh, V_f_mesh, C_T_surface, cmap='viridis', edgecolor='k')
            ax.set_xlabel('alpha_v (radians)')
            ax.set_ylabel('V_f (Forward Flight Speed)')
            ax.set_zlabel('C_T')
            ax.set_title('3D Surface of C_T')

            fig.colorbar(surf, ax=ax, shrink=0.5, aspect=10)
            plt.show()

    def interpolation(self):
        # interpolate with numpy the values of lift and drag as a function of the radius position
        self.dL_r_interp = np.interp(self.r_list, self.r_list, [self.forward(omega=self.omega, theta_r=theta, c_r=chord, r=r, dr=self.dr, V_f=34.93, a_r=a, psi=(1.5 * np.pi), gamma=0.0, alpha_v=0.0, v_fl=0.0)[0] if self.cutout < r < self.r_e else 0.0 for chord, theta, a, r in zip(self.c_r_list, self.theta_r_list, self.a_r_list, self.r_list)])
        self.dD_r_interp = np.interp(self.r_list, self.r_list, [self.forward(omega=self.omega, theta_r=theta, c_r=chord, r=r, dr=self.dr, V_f=34.93, a_r=a, psi=(1.5* np.pi), gamma=0.0, alpha_v=0.0, v_fl=0.0)[1] if self.cutout < r < self.r_e else 0.0 for chord, theta, a, r in zip(self.c_r_list, self.theta_r_list, self.a_r_list, self.r_list)])
        # return the values
        return self.dL_r_interp, self.dD_r_interp

    def induced(self):
        v_r_hov = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 5.613125546549002, 5.850520904347805, 6.078599548671493, 6.297841149640315, 6.508678166592937, 6.711502128191865, 6.906668867475168, 7.09450291729418, 7.275301225408243, 7.449336313922077, 7.616858981560541, 7.7781006272402164, 7.933275257926644, 8.082581231715281, 8.226202777610302, 8.364311325985922, 8.497066677745387, 8.624618035402172, 8.747104915439289, 8.864657958159235, 8.977399648668756, 9.085444960532632, 9.188901931888337, 9.287872182367815, 9.382451377967385, 9.472729649997696, 9.558791973397218, 9.640718508976263, 9.718584913551403, 9.792462621413573, 9.862419100132136, 9.928518083319153, 9.990819782653302, 10.049381081182577, 10.10425570968228, 10.155494407634349, 10.203145070210468, 10.247252882481263, 10.287860441933327, 10.325007870252211, 10.35873291522049, 10.389071043483472, 10.416055524849154, 10.439717508712503, 10.46008609312547, 10.477188386972236, 10.491049565653336, 10.501692920631385, 10.509139903144499, 10.513410162350565, 10.514521578125697, 10.51249028870284, 10.507330713301217, 10.499055569863808, 10.487675887987553, 10.473201017099514, 10.45563862990114, 10.43499472107183, 10.41127360119178, 10.384477885812206, 10.35460847956827, 10.32166455519562, 10.285643527275449, 10.246541020494409, 10.20435083216446, 10.159064888702972, 10.110673195724551, 10.05916378134258, 10.004522632218936, 9.946733621834712, 9.885778430380983, 9.82163645558601, 9.754284713702045, 9.683697729769408, 9.609847416155286, 9.532702938228065, 9.452230565870842, 9.36839350935787, 9.281151737909608, 9.190461779001753, 9.096276496224275, 0.0, 0.0, 0.0, 0.0]
        v_r_avg_hov = sum(v_r_hov)/len(v_r_hov)
        return v_r_avg_hov


if __name__ == '__main__':
    BEMT = BEMT()

    #which analysis
    vertical = True
    forward = False
    interpolation = False
    controlstability = False

    #initialise discretisation and insert number of elements (minimum 100 for accuracy)
    num_elements = 100
    BEMT.discretise(num_elements=num_elements)

    if vertical==True:
        print("––––––––––––––––––––––––––––––––––––––––––––––")
        print("\033[34mVertical Flight:\033[0m")

        #specify vertical flight regime
        V_c = 0.76

        dL_r_list1 = []
        dD_r_list1 = []
        dT_r_list1 = []
        dQ_r_list1 = []
        dP_r_list1 = []
        dFx_r_list1 = []
        alpha_r_list1 = []
        v_r_list1 = []
        stall_r_list1 = []
        M_r_list1 = []

        for chord, theta, a, r in zip(BEMT.c_r_list, BEMT.theta_r_list, BEMT.a_r_list, BEMT.r_list):
            prop_1 = BEMT.vertical(omega=BEMT.omega, theta_r=theta, c_r=chord, r=r, dr=BEMT.dr, a_r=a, V_c=V_c)
            if BEMT.cutout<r<BEMT.r_e:
                dL_r_list1.append(prop_1[0])
                dD_r_list1.append(prop_1[1])
                dT_r_list1.append(prop_1[2])
                dQ_r_list1.append(prop_1[3])
                dP_r_list1.append(prop_1[4])
                dFx_r_list1.append(prop_1[5])
                alpha_r_list1.append(prop_1[6])
                v_r_list1.append(prop_1[7])
                stall_r_list1.append(prop_1[8])
                M_r_list1.append(prop_1[9])
            else:
                dL_r_list1.append(0.0)
                dD_r_list1.append(0.0)
                dT_r_list1.append(0.0)
                dQ_r_list1.append(0.0)
                dP_r_list1.append(0.0)
                dFx_r_list1.append(0.0)
                alpha_r_list1.append(0.0)
                v_r_list1.append(0.0)
                stall_r_list1.append(0.0)
                M_r_list1.append(0.0)

        print(v_r_list1)
        #integration for one blade
        L = sum(dL_r_list1)
        D = sum(dD_r_list1)
        T = sum(dT_r_list1)
        Q = sum(dQ_r_list1)
        P_r = sum(dP_r_list1)
        Fx = sum(dFx_r_list1)

        LD = L / D
        TFx = T / Fx
        C_T = (T * BEMT.b) / (math.pi * (BEMT.R ** 2) * BEMT.rho * ((BEMT.omega * BEMT.R) ** 2))  # for the number of blades
        C_Fx = (Fx * BEMT.b) / (math.pi * (BEMT.R ** 2) * BEMT.rho * ((BEMT.omega * BEMT.R) ** 2))  # for the number of blades
        C_Q = (Q * BEMT.b) / (math.pi * (BEMT.R ** 3) * BEMT.rho * ((BEMT.omega * BEMT.R) ** 2))  # for the number of blades
        C_P = (P_r * BEMT.b) / (math.pi * (BEMT.R ** 2) * BEMT.rho * ((BEMT.omega * BEMT.R) ** 3))  # for the number of blades
        stall_factor = stall_r_list1.count(1)/num_elements
        M_max = max(M_r_list1)

        print("---------------------")
        print(f"V_c {V_c}")
        print(f"omega {BEMT.omega} [rad/s] or {9.549*BEMT.omega} [rpm]")
        print(f"L/D {LD} [-]")
        print(f"T/Fx {TFx} [-]")
        print(f"AR {BEMT.AR} [-]")
        print(f"R {BEMT.R} [m]")
        print(f"C_T {C_T}")
        print(f"C_Fx {C_Fx}")
        print(f"C_Q {C_Q}")
        print(f"C_P {C_P}")
        print(f"Stall occurence {stall_factor}")
        print(f"Maximum mach number {M_max}")
        print("Other units in [N], [N*m], [W]")

        print("---------------------")
        print(f"one blade: (with induced velocity for b={BEMT.b})")
        print(f"L {L} D {D} T {T} Q {Q} P_r {P_r} Fx {Fx}")

        print("---------------------")
        print(f"for {BEMT.b} blades:")
        print(f"L {L*BEMT.b} D {D*BEMT.b} T {T*BEMT.b} Q {Q*BEMT.b} P_r {P_r*BEMT.b}  Fx {Fx*BEMT.b}")

        print("---------------------")
        print(f"for {BEMT.n_rotors} rotors:")
        print(f"L {L * BEMT.b * BEMT.n_rotors} D {D * BEMT.b * BEMT.n_rotors} T {T * BEMT.b * BEMT.n_rotors} Q {Q * BEMT.b * BEMT.n_rotors} P_r {P_r * BEMT.b * BEMT.n_rotors}  Fx {Fx * BEMT.b * BEMT.n_rotors}")

        T_req = (832.034 * 9.80665 * 1.10)/(np.cos(10*(np.pi/180)))
        n_rotor = T_req/(T*BEMT.b)
        print("---------------------")
        print(f"You would need {n_rotor} rotors to generate {T_req} [N] of thrust")

        ######Ideal power
        # x_values = np.linspace(0.15 * BEMT.R, 0.96 * BEMT.R, 100)
        #
        # delta_x = x_values[1] - x_values[0]
        #
        # print(v_r_list1)
        # hi = np.trapz(v_r_list1[14:95]) * delta_x
        list111 = [2.6064851846444075, 2.7625253241373295, 2.913642055425938, 3.0600686364145497, 3.2020178564140505, 3.339684493107723, 3.473247400239225, 3.60287129183786, 3.728708275347019, 3.850899175649772, 3.969574683916361, 4.084856358868647, 4.19685750305276, 4.30568393272721, 4.411434656779716, 4.5142024775091265, 4.61407452401703, 4.711132727246159, 4.805454244300948, 4.897111838529499, 4.986174220887415, 5.0727063573056475, 5.156769746116544, 5.238422669031174, 5.3177204186877765, 5.394715505390457, 5.4694578453166915, 5.541994932181897, 5.612371994100833, 5.680632137172265, 5.746816477129741, 5.810964260242729, 5.873112974514903, 5.933298452107221, 5.991554963809372, 6.04791530629268, 6.102410882797957, 6.155071777842378, 6.20592682646807, 6.255003678501203, 6.302328858242785, 6.347927819970034, 6.391824999589972, 6.434043862753525, 6.474606949708852, 6.5135359171462826, 6.550851577263586, 6.586573934259196, 6.620722218442096, 6.653314918130033, 6.684369809492388, 6.713903984480279, 6.741933876973941, 6.768475287266184, 6.79354340499048, 6.817152830592975, 6.839317595439249, 6.860051180639003, 6.879366534664768, 6.897276089834402, 6.913791777721165, 6.928925043549879, 6.942686859632572, 6.955087737892616, 6.966137741521912, 6.9758464958119815, 6.984223198196032, 6.991276627535713, 6.997015152683133, 7.001446740345707, 7.00457896227862, 7.006419001827043, 7.006973659837711, 7.006249359957145, 7.004252153331403, 7.000987722720169, 6.996461386035752, 6.9906780993155415, 6.983642459134444, 6.975358704461787, 6.965830717965231]
        hi = sum(list111)/len(list111)

        print(hi)
        #v_i = np.sqrt((709.63 * 9.80665 * (1/6))/(2 * 1.225 * np.pi * (1.09**2)))
        v_i = hi
        print(v_i)
        P_i = v_i * (709.63 * 9.80665)
        print(P_i)

        #FM
        FM1 = P_i/(P_r * BEMT.b * BEMT.n_rotors)
        print(f"FM1 = {FM1}")
        FM2 = (C_T/C_P) * (np.sqrt(C_T/2))
        print(f"FM2 = {FM2}")



        plot = True
        if plot==True:
            fig, axes = plt.subplots(4, 1, figsize=(8, 10), sharex=True)

            axes[0].plot(BEMT.r_list, dL_r_list1)
            axes[0].set_ylabel("Lift [N]")

            axes[1].plot(BEMT.r_list, dD_r_list1)
            axes[1].set_ylabel("Drag [N]")

            axes[2].plot(BEMT.r_list, alpha_r_list1)
            axes[2].set_ylabel("alpha [rad]")

            axes[3].plot(BEMT.r_list, v_r_list1)
            axes[3].set_ylabel("Induced velocity [m/s]")
            axes[3].set_xlabel("Radial position [m]")

            plt.show()

    if forward==True:
        print("––––––––––––––––––––––––––––––––––––––––––––––")
        print("\033[32mForward flight:\033[0m")

        #specify forward flight regime
        V_f = 37
        gamma = 0.0
        alpha_v = 0.0 * (np.pi/180) #in radians


        dL_r_list2 = []
        dD_r_list2 = []
        dT_r_list2 = []
        dQ_r_list2 = []
        dP_r_list2 = []
        dFx_r_list2 = []
        alpha_r_list2 = []
        stall_r_list2 = []
        M_r_list2 = []
        dMom_r_list2 = []
        dX_r_list2 = []
        v_r_list2 = []

        dL_r_list3 = []
        dD_r_list3 = []
        dT_r_list3 = []
        dQ_r_list3 = []
        dP_r_list3 = []
        dFx_r_list3 = []
        alpha_r_list3 = []
        stall_r_list3 = []
        M_r_list3 = []
        dMom_r_list3 = []
        dX_r_list3 = []
        v_r_list3 = []


        L = 0
        D = 0
        T = 0
        Q = 0
        P = 0
        Fx = 0
        Mom = 0
        X = 0

        for psi in BEMT.psi_list:
            #print(f"psi = {psi*(180/np.pi)}")
            for chord, theta, a, r in zip(BEMT.c_r_list, BEMT.theta_r_list, BEMT.a_r_list, BEMT.r_list):
                #print(f"r = {r}")
                if BEMT.cutout<r<BEMT.r_e:
                    prop_2 = BEMT.forward(omega=BEMT.omega, theta_r=theta, c_r=chord, r=r, dr=BEMT.dr, a_r=a, V_f=V_f, gamma=gamma, psi=psi, alpha_v=alpha_v, v_fl=0.0)
                    dL_r_list3.append(prop_2[0])
                else:
                    dL_r_list3.append(0.0)

            dL_r_list2.append(dL_r_list3)
            L += sum(dL_r_list3)

            dL_r_list3 = []

        #print(dL_r_list2[30],dL_r_list2[90])
        amp_r = BEMT.flapping(dL_psi90=dL_r_list2[30],dL_psi270=dL_r_list2[90])

        dL_r_list2 = []
        L = 0
        n = 3

        for i in range(n):
            for psi in BEMT.psi_list:
                #print(f"psi = {psi*(180/np.pi)}")
                for chord, theta, a, r in zip(BEMT.c_r_list, BEMT.theta_r_list, BEMT.a_r_list, BEMT.r_list):
                    #print(f"r = {r}")
                    v_fl = amp_r[BEMT.r_list.index(r)] * np.cos(psi) * BEMT.omega
                    #print(v_fl)
                    if BEMT.cutout<r<BEMT.r_e:
                        prop_2 = BEMT.forward(omega=BEMT.omega, theta_r=theta, c_r=chord, r=r, dr=BEMT.dr, a_r=a, V_f=V_f, gamma=gamma, psi=psi, alpha_v=alpha_v, v_fl=v_fl)
                        dL_r_list3.append(prop_2[0])
                        dD_r_list3.append(prop_2[1])
                        dT_r_list3.append(prop_2[2])
                        dQ_r_list3.append(prop_2[3])
                        dP_r_list3.append(prop_2[4])
                        dFx_r_list3.append(prop_2[5])
                        alpha_r_list3.append(prop_2[6])
                        stall_r_list3.append(prop_2[7])
                        M_r_list3.append(prop_2[8])
                        dMom_r_list3.append(prop_2[9])
                        dX_r_list3.append(prop_2[10])
                        v_r_list3.append(prop_2[11])
                    else:
                        dL_r_list3.append(0.0)
                        dD_r_list3.append(0.0)
                        dT_r_list3.append(0.0)
                        dQ_r_list3.append(0.0)
                        dP_r_list3.append(0.0)
                        dFx_r_list3.append(0.0)
                        alpha_r_list3.append(0.0)
                        stall_r_list3.append(0.0)
                        M_r_list3.append(0.0)
                        dMom_r_list3.append(0.0)
                        dX_r_list3.append(0.0)
                        v_r_list3.append(0.0)

                dL_r_list2.append(dL_r_list3)
                L += sum(dL_r_list3)

                dD_r_list2.append(dD_r_list3)
                D += sum(dD_r_list3)

                dT_r_list2.append(dT_r_list3)
                T += sum(dT_r_list3)

                dQ_r_list2.append(dQ_r_list3)
                Q += sum(dQ_r_list3)

                dP_r_list2.append(dP_r_list3)
                P += sum(dP_r_list3)

                dFx_r_list2.append(dFx_r_list3)
                Fx += sum(dFx_r_list3)

                alpha_r_list2.append(alpha_r_list3)
                stall_r_list2.append(stall_r_list3.count(1))
                M_r_list2.append(max(M_r_list3))

                dMom_r_list2.append(dMom_r_list3)
                Mom += sum(dMom_r_list3)

                dX_r_list2.append(dX_r_list3)
                X += sum(dX_r_list3)

                v_r_list2.append(v_r_list3)

                dL_r_list3 = []
                dD_r_list3 = []
                dT_r_list3 = []
                dQ_r_list3 = []
                dP_r_list3 = []
                dFx_r_list3 = []
                alpha_r_list3 = []
                stall_r_list3 = []
                M_r_list3 = []
                dMom_r_list3 = []
                dX_r_list3 = []
                v_r_list3 = []

            #print(dL_r_list2[30])
            amp_r = BEMT.flapping(dL_psi90=dL_r_list2[30],dL_psi270=dL_r_list2[90])
            #print(f"v_r{v_r_list2}")
            if i != (n - 1):
                dL_r_list2 = []
                dD_r_list2 = []
                dT_r_list2 = []
                dQ_r_list2 = []
                dP_r_list2 = []
                dFx_r_list2 = []
                alpha_r_list2 = []
                stall_r_list2 = []
                M_r_list2 = []
                dMom_r_list2 = []
                dX_r_list2 = []

                L = 0
                D = 0
                T = 0
                Q = 0
                P = 0
                Fx = 0
                Mom = 0
                X = 0


        #print(stall_r_list2)
        L = L / BEMT.psi_elements
        D = D / BEMT.psi_elements
        T = T / BEMT.psi_elements
        Q = Q / BEMT.psi_elements
        P = P / BEMT.psi_elements
        Fx = Fx / BEMT.psi_elements
        Mom = Mom / BEMT.psi_elements
        X = X / BEMT.psi_elements

        print(f"X= {X*BEMT.b}")
        LD = L / D
        TFx = T / Fx
        stall_factor = sum(stall_r_list2)/(num_elements*BEMT.psi_elements)
        M_max = max(M_r_list2)

        C_T = (T * BEMT.b)/ (math.pi * (BEMT.R ** 2) * BEMT.rho * ((BEMT.omega * BEMT.R) ** 2)) #for the number of blades
        C_Fx = (Fx * BEMT.b) / (math.pi * (BEMT.R ** 2) * BEMT.rho * ((BEMT.omega * BEMT.R) ** 2))# for the number of blades
        C_X = (X * BEMT.b) / (math.pi * (BEMT.R ** 2) * BEMT.rho * ((BEMT.omega * BEMT.R) ** 2))# for the number of blades
        C_Q = (Q * BEMT.b) / (math.pi * (BEMT.R ** 3) * BEMT.rho * ((BEMT.omega * BEMT.R) ** 2))# for the number of blades
        C_P = (P * BEMT.b) / (math.pi * (BEMT.R ** 2) * BEMT.rho * ((BEMT.omega * BEMT.R) ** 3))# for the number of blades

        print("---------------------")
        print(f"V_f {V_f} [m/s]")
        print(f"gamma {gamma}")
        print(f"alpha_v {alpha_v}")
        print(f"omega {BEMT.omega} [rad/s] or {9.549 * BEMT.omega} [rpm]")
        print(f"L/D {LD} [-]")
        print(f"T/Fx {TFx} [-]")
        print(f"AR {BEMT.AR} [-]")
        print(f"R {BEMT.R} [m]")
        print(f"C_T rotor {C_T}")
        print(f"C_Fx rotor {C_Fx}")
        print(f"C_X rotor {C_X}")
        print(f"C_Q rotor {C_Q}")
        print(f"C_P rotor {C_P}")
        print(f"Stall occurence {stall_factor}")
        print(f"Maximum mach number {M_max}")
        print(f"Moment {Mom * BEMT.b}")
        print("Other units in [N], [N*m], [W]")

        print("---------------------")
        print(f"one blade: (with induced velocity for b={BEMT.b})")
        print(f"L {L} D {D} T {T} Q {Q} P {P} Fx {Fx}")

        print("---------------------")
        print(f"for {BEMT.b} blades:")
        print(f"L {L * BEMT.b} D {D * BEMT.b} T {T * BEMT.b} Q {Q * BEMT.b} P_r {P * BEMT.b}  Fx {Fx * BEMT.b}")

        print("---------------------")
        print(f"for {BEMT.n_rotors} rotors:")
        print(f"L {L * BEMT.b * BEMT.n_rotors} D {D * BEMT.b * BEMT.n_rotors} T {T * BEMT.b * BEMT.n_rotors} Q {Q * BEMT.b * BEMT.n_rotors} P_r {P * BEMT.b * BEMT.n_rotors}  Fx {Fx * BEMT.b * BEMT.n_rotors}")

        T_req = (832.034 * 9.80665 * 1.10) / (np.cos(10 * (np.pi / 180)))
        n_rotor = T_req / (T * BEMT.b)
        print("---------------------")
        print(f"You would need {n_rotor} rotors to generate {T_req} [N] of thrust")

        plot = True
        if plot == True:

            plt.plot(BEMT.r_list, dL_r_list2[0])
            plt.plot(BEMT.r_list, dL_r_list2[30], color='k')
            plt.plot(BEMT.r_list, dL_r_list2[60], color='r')
            plt.plot(BEMT.r_list, dL_r_list2[90], color='b')
            haha = [(x + y + z + t)/4 for x, y, z, t in zip(dL_r_list2[0], dL_r_list2[30], dL_r_list2[60], dL_r_list2[90])]
            plt.plot(BEMT.r_list, haha, color='b')

            plt.show()

            plt.plot(BEMT.r_list, alpha_r_list2[0])
            plt.plot(BEMT.r_list, alpha_r_list2[30],color='k')
            plt.plot(BEMT.r_list, alpha_r_list2[60])
            plt.plot(BEMT.r_list, alpha_r_list2[90],color='b')
            plt.show()

    if interpolation==True:
        #interpolate lift and drag
        dL_r_interp, dD_r_interp = BEMT.interpolation()

        # Fit a polynomial of the given degree
        coefficients = np.polyfit(BEMT.r_list, dL_r_interp, 1)

        # Create a polynomial function from the coefficients
        polynomial = np.poly1d(coefficients)

        # Generate a range of x values for interpolation
        x_interp = np.linspace(BEMT.cutout, BEMT.r_bar_e * BEMT.R, 100)

        # Use the polynomial to calculate the interpolated y values
        y_interp = polynomial(x_interp)

        # Plot the original data points and the interpolated curve
        plt.plot(BEMT.r_list, dL_r_interp, label='Original data')
        plt.plot(x_interp, y_interp, label=f'Polynomial degree {30}')
        plt.legend()
        plt.xlabel('X')
        plt.ylabel('Y')
        plt.title('Polynomial Interpolation')
        plt.grid(True)
        print(sum(dL_r_interp))
        print(sum(dD_r_interp))
        plt.show()


        # # Find the index corresponding to the cutout
        # cutout_index = next(i for i, r in enumerate(BEMT.r_list) if r > BEMT.cutout)
        #
        # # Find the maximum values of lift and drag
        # max_lift = max(dL_r_interp)
        # max_drag = max(dD_r_interp)
        #
        # # Find the indices of the maximum values
        # max_lift_index = np.argmax(dL_r_interp)
        # max_drag_index = np.argmax(dD_r_interp)
        #
        # # Calculate the slope and intercept for lift
        # m_lift = (max_lift - dL_r_interp[cutout_index]) / (BEMT.r_list[max_lift_index] - BEMT.r_list[cutout_index])
        # b_lift = dL_r_interp[cutout_index] - m_lift * BEMT.r_list[cutout_index]
        #
        # # Calculate the slope and intercept for drag
        # m_drag = (max_drag - dD_r_interp[cutout_index]) / (BEMT.r_list[max_drag_index] - BEMT.r_list[cutout_index])
        # b_drag = dD_r_interp[cutout_index] - m_drag * BEMT.r_list[cutout_index]
        #
        # # Generate polynomial equations
        # poly_eq_lift = np.poly1d([m_lift, b_lift])
        # poly_eq_drag = np.poly1d([m_drag, b_drag])
        #
        # print("Equation for interpolated Lift (dL):")
        # print(poly_eq_lift)
        #
        # print("Equation for interpolated Drag (dD):")
        # print(poly_eq_drag)


        # fig, axes = plt.subplots(2, 1, figsize=(8, 6), sharex=True)
        #
        # axes[0].plot(BEMT.r_list, dL_r_interp, label='Interpolated Lift')
        # axes[0].plot(BEMT.r_list, poly_eq_lift(BEMT.r_list), label='Polynomial Fit Lift', linestyle='--')
        # axes[0].set_ylabel("Lift [N]")
        # axes[0].legend()
        #
        # axes[1].plot(BEMT.r_list, dD_r_interp, label='Interpolated Drag', color='r')
        # axes[1].plot(BEMT.r_list, poly_eq_drag(BEMT.r_list), label='Polynomial Fit Drag', linestyle='--', color='orange')
        # axes[1].set_ylabel("Drag [N]")
        # axes[1].set_xlabel("Radial position [m]")
        # axes[1].legend()
        #
        # plt.show()
        # BEMT.controlstability()

    if controlstability==True:
        BEMT.controlstability()

